### ISSUE TITLE
Add option to specify output directory for cabal file

### ISSUE THREAD

**Issue by locallycompact** [cabalism/hpack-dhall#38]
I'm dealing with a situation where the dhall is coming from nowhere in particular, but the cabal file needs to be put in a particular directory. Does hpack even allow this? I know it can output to stdout.

**Comment by philderbeast** [comment]
I've only ever put the `package.dhall` in the folder where I want to generate the cabal file. Can you write it there temporarily? It doesn't have to be named `package.yaml`.

**Comment by locallycompact** [comment]
Oh of course, it must do. Thanks.
